//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Authoriza
    {
        public int id { get; set; }
        public int id_Account_Type { get; set; }
        public int id_Action { get; set; }
    
        public virtual Account_Type Account_Type { get; set; }
        public virtual Action Action { get; set; }
    }
}
