//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hot_Trend
    {
        public int id { get; set; }
        public Nullable<int> id_Watch { get; set; }
        public Nullable<int> id_Shop { get; set; }
        public string Image { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<bool> IsLock { get; set; }
    
        public virtual Shops Shops { get; set; }
        public virtual Watches Watches { get; set; }
    }
}
