//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Server.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Watches_Categories
    {
        public int id_Watch { get; set; }
        public int id_Category { get; set; }
        public string Detail { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Watches Watches { get; set; }
    }
}
