//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int id { get; set; }
        public int id_Account { get; set; }
        public string id_Province { get; set; }
        public string id_District { get; set; }
        public string AddressDetail { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Address_District Address_District { get; set; }
        public virtual Address_Province Address_Province { get; set; }
    }
}
