//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeeWatchDBEntities : DbContext
    {
        public BeeWatchDBEntities()
            : base("name=BeeWatchDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Type> Account_Type { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<Address> Address { get; set; }
        public virtual DbSet<Address_District> Address_District { get; set; }
        public virtual DbSet<Address_Province> Address_Province { get; set; }
        public virtual DbSet<Authoriza> Authoriza { get; set; }
        public virtual DbSet<CartDetails> CartDetails { get; set; }
        public virtual DbSet<Carts> Carts { get; set; }
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Hot_Trend> Hot_Trend { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<LogInHistories> LogInHistories { get; set; }
        public virtual DbSet<OrderDetails> OrderDetails { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Phone> Phone { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<Sex> Sex { get; set; }
        public virtual DbSet<Shop_Seller> Shop_Seller { get; set; }
        public virtual DbSet<Shops> Shops { get; set; }
        public virtual DbSet<TypeDiscounts> TypeDiscounts { get; set; }
        public virtual DbSet<Watches> Watches { get; set; }
    }
}
