//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BeeWatchDataBaseEntities : DbContext
    {
        public BeeWatchDataBaseEntities()
            : base("name=BeeWatchDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account_Type> Account_Type { get; set; }
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Authoriza> Authoriza { get; set; }
        public virtual DbSet<Bills> Bills { get; set; }
        public virtual DbSet<Bought> Bought { get; set; }
        public virtual DbSet<Cart> Cart { get; set; }
        public virtual DbSet<Commodities> Commodities { get; set; }
        public virtual DbSet<Discounts> Discounts { get; set; }
        public virtual DbSet<Firms> Firms { get; set; }
        public virtual DbSet<Hot_Trend> Hot_Trend { get; set; }
        public virtual DbSet<Image> Image { get; set; }
        public virtual DbSet<Sellers> Sellers { get; set; }
        public virtual DbSet<Watches> Watches { get; set; }
    }
}
