//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bills
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Bills()
        {
            this.Bought = new HashSet<Bought>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_Accounts { get; set; }
        public Nullable<System.DateTime> Datetime { get; set; }
        public Nullable<int> id_Discounts { get; set; }
        public Nullable<double> Sum { get; set; }
        public Nullable<double> Ship_fee { get; set; }
        public string Payment { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Discounts Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bought> Bought { get; set; }
    }
}
