//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carts
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carts()
        {
            this.WatchesinCarts = new HashSet<WatchesinCarts>();
        }
    
        public int id { get; set; }
        public Nullable<int> id_discounts { get; set; }
        public string Address { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Sum { get; set; }
    
        public virtual Accounts Accounts { get; set; }
        public virtual Discounts Discounts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WatchesinCarts> WatchesinCarts { get; set; }
    }
}
