//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Local.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_UserSeller
    {
        public int id { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Url_Image_Avatar { get; set; }
        public string Identitycard { get; set; }
        public string Bankcard { get; set; }
    }
}
