//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Local.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_AllOrderDetail
    {
        public Nullable<int> id_Order { get; set; }
        public Nullable<int> id_Accounts { get; set; }
        public string Fullname { get; set; }
        public string Email { get; set; }
        public string Address_District { get; set; }
        public string Address_Province { get; set; }
        public string AddressDetail { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<double> Sum { get; set; }
        public Nullable<int> SoLuongTong { get; set; }
        public string Payment { get; set; }
        public int id_OrderDetail { get; set; }
        public Nullable<int> id_Watches { get; set; }
        public Nullable<int> SoLuongSP { get; set; }
        public Nullable<double> Price { get; set; }
        public int TonKho { get; set; }
        public Nullable<int> id_Discount { get; set; }
        public Nullable<double> Value___ { get; set; }
        public Nullable<double> Value___1 { get; set; }
        public string Code_Discounts { get; set; }
    }
}
