//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Local.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_CartDetailHome
    {
        public int id_Watch { get; set; }
        public int id_Cart { get; set; }
        public int Count { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public string Url_Image { get; set; }
    }
}
