//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Local.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_Watches
    {
        public Nullable<int> id { get; set; }
        public string WatchName { get; set; }
        public Nullable<int> Count { get; set; }
        public string Url_Image { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Rate { get; set; }
        public string Information { get; set; }
        public Nullable<int> id_Shop { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public string NameofSex { get; set; }
        public string NameofFirm { get; set; }
        public Nullable<int> LuotMua { get; set; }
    }
}
