//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API_Local.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_WatchDetails
    {
        public int id { get; set; }
        public string Url_Image { get; set; }
        public Nullable<int> id_Sex { get; set; }
        public int id_Firms { get; set; }
        public string Name { get; set; }
        public double Price { get; set; }
        public int Count { get; set; }
        public string Information { get; set; }
        public int id_Shop { get; set; }
        public Nullable<double> Rate { get; set; }
        public Nullable<System.DateTime> Date_Create { get; set; }
        public string Create_By { get; set; }
        public Nullable<System.DateTime> Date_LastEdit { get; set; }
        public string LastEdit_By { get; set; }
        public Nullable<bool> IsLock { get; set; }
        public Nullable<bool> IsCheck { get; set; }
        public Nullable<bool> IsExist { get; set; }
        public string Name_Categories { get; set; }
        public string Name_Phai { get; set; }
        public string Name_Firms { get; set; }
        public Nullable<int> LuotMua { get; set; }
    }
}
